version: "3.8"

x-restart-policy: &restart_policy
  restart: unless-stopped

services:
  sage:
    << : *restart_policy
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/onerandomusername/sage:latest
    container_name: sage
    init: true
    tty: true
    ports:
      - "8000:8000"

    volumes:
      - ./src:/sage/src
